name: Build RPM Package

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Make helloworld executable
        run: chmod +x helloworld

      - name: Install RPM
        run: sudo apt-get install rpm -y

      - name: Build RPM package
        run: |
          rpmbuild -ba --build-in-place --define "_topdir $(pwd)/rpm" helloworld.spec
          mv rpm/SRPMS/*.rpm .
          mv rpm/RPMS/*/*.rpm .
          rm -rf rpm
      - name: Upload RPM artifact
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-rpm
          path: '*.rpm'
